-- require('lsp-inlayhints').setup()
-- local augroup = require('user.utils').augroup
-- local autocmd = require('user.utils').autocmd
-- local lsp_augroup = augroup('LSP_preferences', { clear = true })
-- autocmd('LspAttach', {
--         group = lsp_augroup,
--         callback = function(args)
--                 print('LspAttach')
--                 if not (args.data and args.data.client_id) then
--                         return
--                 end
--
--                 local bufnr = args.buf
--                 local client = vim.lsp.get_client_by_id(args.data.client_id)
--
--                 require('lsp-inlayhints').on_attach(client, bufnr)
--                 if client == nil then
--                         return
--                 end
--                 if client.server_capabilities.codeLensProvider then
--                         autocmd({ 'BufEnter', 'CursorHold', 'InsertLeave' }, {
--                                 group = lsp_augroup,
--                                 buffer = bufnr,
--                                 callback = vim.lsp.codelens.refresh,
--                         })
--                 end
--         end,
-- })
