return {
    {
        'simrat39/symbols-outline.nvim',
        opts = {
            highlight_hovered_item = true,
            show_guides = true,
            auto_preview = false,
            position = 'right',
            relative_width = true,
            auto_close = false,
            show_numbers = false,
            show_relative_numbers = false,
            show_symbol_details = true,
            preview_bg_highlight = 'Pmenu',
            autofold_depth = nil,
            auto_unfold_hover = true,
            fold_markers = { '', '' },
            wrap = false,
            keymaps = { -- These keymaps can be a string or a table for multiple keys
                close = { '<Esc>', 'q' },
                goto_location = '<Cr>',
                focus_location = 'o',
                hover_symbol = '<C-space>',
                toggle_preview = 'K',
                rename_symbol = 'r',
                code_actions = 'a',
                fold = 'h',
                unfold = 'l',
                fold_all = 'W',
                unfold_all = 'E',
                fold_reset = 'R',
            },
            lsp_blacklist = {},
            symbol_blacklist = {},
            symbols = {
                File = { icon = 'f', hl = '@text.uri' },
                Module = { icon = 'M', hl = '@namespace' },
                Namespace = { icon = '', hl = '@namespace' },
                Package = { icon = '', hl = '@namespace' },
                Class = { icon = 'Class', hl = '@type' },
                Method = { icon = 'method', hl = '@method' }, -- Updated method icon
                Property = { icon = 'Property', hl = '@method' },
                Field = { icon = 'Field', hl = '@field' },
                Constructor = { icon = '', hl = '@constructor' },
                Enum = { icon = 'Enum', hl = '@type' },
                Interface = { icon = 'I', hl = '@type' },
                Function = { icon = 'ƒ', hl = '@function' },
                Variable = { icon = 'V', hl = '@constant' },
                Constant = { icon = 'C', hl = '@constant' },
                String = { icon = 'S', hl = '@string' },
                Number = { icon = '#', hl = '@number' },
                Boolean = { icon = 'B', hl = '@boolean' },
                Array = { icon = 'A', hl = '@constant' },
                Object = { icon = 'O', hl = '@type' },
                Key = { icon = 'K', hl = '@type' },
                Null = { icon = 'NULL', hl = '@type' },
                EnumMember = { icon = 'E', hl = '@field' },
                Struct = { icon = 'S', hl = '@type' },
                Event = { icon = 'E', hl = '@type' },
                Operator = { icon = '+', hl = '@operator' },
                TypeParameter = { icon = 'T', hl = '@parameter' },
                Component = { icon = 'C', hl = '@function' },
                Fragment = { icon = 'F', hl = '@constant' },
            },
        },
    },
}
