-- local plugin = 'glow'
-- local is_installed, glow = pcall(require, plugin)
-- if not is_installed then
--         return
-- end
--
-- local glow_path = os.getenv("HOMEBREW_PREFIX") .. "/bin/glow"
--
-- local defaults_opts = {
--         glow_path = glow_path,
--         install_path = glow_path,
--         style = "dark",
--         width = 100,
-- }
--
-- glow.setup(defaults_opts)
