-- #keymaps
vim.g.timeout = true
vim.o.timeoutlen = 50
vim.o.ttimeoutlen = 50

local which_key = require("which-key")
-- local default_opts = {
--     plugins = {
--         marks = true, -- shows a list of your marks on ' and `
--         registers = true, -- shows your registers on " in NORMAL or <C-r> in INSERT mode
--         spelling = {
--             enabled = true, -- enabling this will show WhichKey when pressing z= to select spelling suggestions
--             suggestions = 100, -- how many suggestions should be shown in the list?
--         },
--         -- the presets plugin, adds help for a bunch of default keybindings in Neovim
--         -- No actual key bindings are created
--         presets = {
--             operators = true, -- adds help for operators like d, y, ... and registers them for motion / text object completion
--             motions = true, -- adds help for motions
--             text_objects = true, -- help for text objects triggered after entering an operator
--             windows = true, -- default bindings on <c-w>
--             nav = true, -- misc bindings to work with windows
--             z = true, -- bindings for folds, spelling and others prefixed with z
--             g = true, -- bindings for prefixed with g
--         },
--     },
--     motions = {
--         count = true,
--     },
--     -- add operators that will trigger motion and text object completion
--     -- to enable all native operators, set the preset / operators plugin above
--     operators = { gc = "Comments" },
--     icons = {
--         breadcrumb = "»", -- symbol used in the command line area that shows your active key combo
--         separator = "･", -- symbol used between a key and it's label
--         group = "...", -- symbol prepended to ajd
--     },
--     popup_mappings = {
--         scroll_down = "<c-d>", -- binding to scroll down inside the popup
--         scroll_up = "<c-u>", -- binding to scroll up inside the popup
--     },
--     window = {
--         border = "shadow", -- none, single, double, shadow
--         position = "top", -- bottom, top
--         margin = { 0, 0, 0, 0 }, -- extra window margin [top, right, bottom, left]
--         padding = { 1, 0, 0, 0 }, -- extra window padding [top, right, bottom, left]
--         winblend = 0,
--         zindex = 1000,
--     },
--     layout = {
--         height = { min = 25, max = 25 }, -- min and max height of the columns
--         width = { min = 100, max = 100 }, -- min and max width of the columns
--         spacing = 1, -- spacing between columns
--         align = "left", -- align columns left, center or right
--     },
--     ignore_missing = false, -- enable this to hide mappings for which you didn't specify a label
--     hidden = { "<silent>", "<cmd>", "<Cmd>", "<CR>", "call", "lua", "^:", "^ " }, -- hide mapping boilerplate
--     show_help = true, -- show help message on the command line when the popup is visible
--     show_keys = true, -- show the currently pressed key and its label as a message in the command line
--     triggers = "auto", -- automatically setup triggers
--     -- triggers = {"<leader>"} -- or specify a list manually
--     triggers_blacklist = {
--         -- list of mode / prefixes that should never be hooked by WhichKey
--         -- this is mostly relevant for key maps that start with a native binding
--         -- most people should not need to change this
--         i = { "j", "k" },
--         v = { "j", "k" },
--     },
--     -- disable the WhichKey popup for certain buf types and file types.
--     -- Disabled by deafult for Telescope
--     disable = {
--         buftypes = {},
--         filetypes = {
--             --- Disable in Telescope
--             "TelescopePrompt",
--             --- Disable in command line
--             "vim",
--             "help",
--         },
--     },
-- }
which_key.setup()
